### ISSUE TITLE
修改其他学校可以不？

### ISSUE THREAD

**Issue by KingBoyAndGirl** [nonlinearthink/automatic_health_punch_script#4]
我们学校是钉钉智能填表，能不能用你这个或者魔改？

**Comment by nonlinearthink** [comment]
可以的吧，只要改 [__init__.py](https://github.com/nonlinearthink/automatic_health_punch_script/blob/master/job/__init__.py) 里面的daka函数就好了，其他都可以复用

**Comment by wtj-0527** [comment]
访问这个获取不到智能填表页面，(ttps://im.dingtalk.com/),
大佬有没有解决方
![BE7FEBFC6604D6B0ECF1B4886BA142B7](https://user-images.githubusercontent.com/48237066/138214243-887ecafe-b754-4702-9951-038f501d6c8a.png)
案

**Comment by nonlinearthink** [comment]
> 访问这个获取不到智能填表页面，(ttps://im.dingtalk.com/), 大佬有没有解决方 ![BE7FEBFC6604D6B0ECF1B4886BA142B7](https://user-images.githubusercontent.com/48237066/138214243-887ecafe-b754-4702-9951-038f501d6c8a.png) 案

你可以模拟登陆钉钉后访问试试，这个必须要在web上能访问到的，如果只能在钉钉访问，可能不太适用这个项目。

**Comment by wtj-0527** [comment]
网页版登陆后也没有没成功，不过还是谢谢你了

**Comment by nonlinearthink** [comment]
好的
